# Generated by Django 4.2.8 on 2023-12-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zainteresowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('numer_sali', models.IntegerField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Zainteresowania',
            },
        ),
        migrations.CreateModel(
            name='Uczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonim', models.CharField(max_length=200)),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('klasa', models.CharField(max_length=200)),
                ('zainteresowania', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.zainteresowania')),
            ],
            options={
                'verbose_name_plural': 'Uczeń',
            },
        ),
    ]
