# Generated by Django 4.2.11 on 2024-03-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ryby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('wystepowanie', models.CharField(max_length=255)),
                ('styl_zycia', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ryby',
            },
        ),
        migrations.CreateModel(
            name='Okres_ochronny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_miesiaca', models.IntegerField()),
                ('do_miesiaca', models.IntegerField()),
                ('wymiar_ochronny', models.IntegerField()),
                ('ryby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rybyapp.ryby')),
            ],
            options={
                'verbose_name_plural': 'Okres_ochronny',
            },
        ),
    ]
