# Generated by Django 4.2.10 on 2024-02-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pracownicy',
            options={'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='stanowiska',
            options={'verbose_name_plural': 'Stanowiska'},
        ),
    ]
