# Generated by Django 4.2.6 on 2023-10-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwisko', models.CharField(max_length=200)),
                ('imie', models.CharField(max_length=200)),
                ('miasto', models.CharField(default='Białystok', max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('wiek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('zalecenia', models.CharField(max_length=200)),
                ('pacjent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='szpital.pacjent')),
            ],
        ),
    ]
