# Generated by Django 4.2.5 on 2023-10-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotkania', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedagog',
            options={'verbose_name_plural': 'Pedagog'},
        ),
        migrations.AlterModelOptions(
            name='spotkania',
            options={'verbose_name_plural': 'Spotkania'},
        ),
        migrations.AlterModelOptions(
            name='uczen',
            options={'ordering': ('imie', 'nazwisko', 'klasa'), 'verbose_name_plural': 'Uczeń'},
        ),
    ]
