# Generated by Django 4.2.5 on 2023-10-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotkania', '0002_alter_pedagog_options_alter_spotkania_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uczen',
            options={'ordering': ('-imie', '-nazwisko', '-klasa'), 'verbose_name_plural': 'Uczeń'},
        ),
    ]
