# Generated by Django 4.2.5 on 2023-10-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotkania', '0003_alter_uczen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uczen',
            options={'ordering': ('imie', 'nazwisko', 'klasa'), 'verbose_name_plural': 'Uczeń'},
        ),
    ]
