# Generated by Django 4.2.16 on 2024-09-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Potrawy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Rodzina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Grzyby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255)),
                ("potoczna", models.CharField(max_length=255)),
                ("jadalny", models.CharField(max_length=255)),
                ("miesiac_zbierania", models.CharField(max_length=255)),
                (
                    "potrawy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grzybyapp.potrawy",
                    ),
                ),
                (
                    "rodzina_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grzybyapp.rodzina",
                    ),
                ),
            ],
        ),
    ]
