# Generated by Django 4.2.16 on 2024-09-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Uzytkownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=100)),
                ("nazwisko", models.CharField(max_length=100)),
                ("telefon", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=100)),
            ],
            options={"verbose_name_plural": "Uzytkownik"},
        ),
        migrations.CreateModel(
            name="Ogloszenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kategoria", models.PositiveSmallIntegerField()),
                ("podkategoria", models.PositiveSmallIntegerField()),
                ("tytul", models.CharField(max_length=100)),
                ("tresc", models.TextField(max_length=100)),
                (
                    "uzytkownik_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oglapp.uzytkownik",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Ogloszenia"},
        ),
    ]
