# Generated by Django 4.2.11 on 2024-04-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolor', models.CharField(max_length=255)),
                ('cena', models.IntegerField()),
                ('pojemnosc', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'farby',
            },
        ),
        migrations.CreateModel(
            name='malowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pomieszczenia', models.IntegerField()),
                ('id_sciany', models.IntegerField()),
                ('liczba_puszek', models.IntegerField()),
                ('id_farby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farbaapp.farby')),
            ],
            options={
                'verbose_name_plural': 'malowanie',
            },
        ),
    ]
