# Generated by Django 4.2.16 on 2024-10-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dyspozytorzy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=100)),
                ("naziwsko", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ratownicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numerKaretki", models.PositiveIntegerField()),
                ("ratownik1", models.TextField(max_length=100)),
                ("ratownik2", models.TextField(max_length=100)),
                ("ratownik3", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Zgloszenia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adres", models.TextField()),
                ("pilne", models.BooleanField()),
                ("czas_zgloszenia", models.TimeField()),
                (
                    "dyspozytorzy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pogapp.dyspozytorzy",
                    ),
                ),
                (
                    "ratownicy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pogapp.ratownicy",
                    ),
                ),
            ],
        ),
    ]
